[project]
name = "whisper-app"
version = "0.1.0"
description = "proto"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.29.5",
    "gradio>=4.44.1",
    "openai-whisper>=20240930",
    "torch>=2.5.0",
    "soundfile>=0.12.1",
]
